version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: src
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker Build
          command: docker build -f Dockerfile -t chinodesuuu/just-monika:latest .
      - run:
          name: Docker Push
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/monika-ws:latest 
